/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/all-ev-pos.ml
*/

%HES
MAIN_7  =v
  (arg1_54 >= 0 \/ SUM (0 - arg1_54) 0 0 (\main0_50.\main10_51.\main11_52.true))
  /\ (arg1_54 < 0 \/ SUM arg1_54 0 0 (\main0_50.\main10_51.\main11_52.true)).
SUM x cfg20 cfg21 k =v
  (\f_69.(x > 0 \/ f_69 (k 0 0 0)) /\ (x <= 0 \/ f_69 (SUM (x - 1) 0 0 (\r_47.\r1_48.\r2_49.k 0 r1_48 r2_49))))
   (\x_66.
     (\f_68.(x > 0 \/ f_68 (k 0 1 0)) /\ (x <= 0 \/ f_68 (SUM (x - 1) 1 0 (\r_47.\r1_48.\r2_49.k 0 r1_48 r2_49))))
      (\x_67.
        x >= 0 /\ (x < 0 \/ (x > 0 \/ k 0 0 0) /\ (x <= 0 \/ SUM (x - 1) 0 0 (\r_47.\r1_48.\r2_49.k 0 r1_48 r2_49))))).
Forall p      =v ∀n. p n.
