/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/all-ev-pos.ml
*/

%HES
MAIN_5  =v
  (arg1_61 >= 0 \/ SUM (0 - arg1_61) 0 0 (\main0_57.\main10_58.\main11_59.true))
  /\ (arg1_61 < 0 \/ SUM arg1_61 0 0 (\main0_57.\main10_58.\main11_59.true)).
SUM x cfg20 cfg21 k =v
  (\f_93.(x > 0 \/ f_93 (k 0 0 0)) /\ (x <= 0 \/ f_93 (SUM (x - 1) 0 0 (\x2_69.\x21_70.\x22_71.k 0 x21_70 x22_71))))
   (\x_90.
     (\f_92.(x > 0 \/ f_92 (k 0 1 0)) /\ (x <= 0 \/ f_92 (SUM (x - 1) 1 0 (\x2_69.\x21_70.\x22_71.k 0 x21_70 x22_71))))
      (\x_91.
        x >= 0
        /\ (x < 0 \/ (x > 0 \/ k 0 0 0) /\ (x <= 0 \/ SUM (x - 1) 0 0 (\x2_69.\x21_70.\x22_71.k 0 x21_70 x22_71))))).
Forall p      =v ∀n. p n.
