/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/alt-inev.ml
*/

%HES
MAIN_14  =v LIFE arg1_278 0 0 (\r_147.\r1_148.\r2_149.r1_148 = 3 \/ r1_148 = 5).
APP h x1 x2 cfg30 cfg31 k =v h x1 (\j_299.\k_300.k_300 (j_299 - x2)) cfg30 cfg31 k.
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 \/ evx != 1) /\ (cfg00 != 1 \/ evx != 1) \/ k 1 0)
  /\ ((cfg00 = 0 /\ evx = 1 \/ cfg00 = 1 /\ evx = 1)
      \/ ((cfg00 != 1 \/ evx != 2) /\ (cfg00 != 2 \/ evx != 2) \/ k 2 0)
         /\ ((cfg00 = 1 /\ evx = 2 \/ cfg00 = 2 /\ evx = 2)
             \/ ((cfg00 != 2 \/ evx != 3) \/ k 3 0)
                /\ (cfg00 = 2 /\ evx = 3
                    \/ ((cfg00 != 1 \/ evx != 4) /\ (cfg00 != 4 \/ evx != 4) \/ k 4 0)
                       /\ ((cfg00 = 1 /\ evx = 4 \/ cfg00 = 4 /\ evx = 4)
                           \/ ((cfg00 != 4 \/ evx != 5) \/ k 5 0) /\ (cfg00 = 4 /\ evx = 5 \/ k 6 0))))).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 >= 6 \/ k true) /\ cfg10 < 6.
LIFE x cfg160 cfg161 k =v
  Forall
   (\n_301.
     (n_301 != 0
      \/ EV_STEP0 1 cfg160 cfg161
          (\cfg170_275.
            \cfg171_276.
             EV_STEP_ASST0 cfg170_275 cfg171_276
              (\x1_144.
                (x >= 0
                 \/ APP WALK x 1 cfg170_275 cfg171_276
                     (\r_173.
                       \r1_174.
                        \r2_175.
                         EV_STEP0 3 r1_174 r2_175
                          (\cfg50_220.
                            \cfg51_221.EV_STEP_ASST0 cfg50_220 cfg51_221 (\x2_256.k x2_256 cfg50_220 cfg51_221))))
                /\ (x < 0
                    \/ APP RUN x 1 cfg170_275 cfg171_276
                        (\r_183.
                          \r1_184.
                           \r2_185.
                            EV_STEP0 5 r1_184 r2_185
                             (\cfg70_232.
                               \cfg71_233.EV_STEP_ASST0 cfg70_232 cfg71_233 (\x2_269.k x2_269 cfg70_232 cfg71_233)))))))
     /\ (n_301 = 0 \/ LIFE x cfg160 cfg161 k)).
RUN y f cfg120 cfg121 k =v
  EV_STEP0 4 cfg120 cfg121
   (\cfg130_284.
     \cfg131_285.
      EV_STEP_ASST0 cfg130_284 cfg131_285
       (\x_157.
         (y >= 0 \/ k 0 cfg130_284 cfg131_285)
         /\ (y < 0 \/ f y (\x1_200.f x1_200 (\x2_243.RUN x2_243 f cfg130_284 cfg131_285 k))))).
WALK z g cfg80 cfg81 k =v
  EV_STEP0 2 cfg80 cfg81
   (\cfg90_291.
     \cfg91_292.
      EV_STEP_ASST0 cfg90_291 cfg91_292
       (\x_165.(z >= 0 \/ k 0 cfg90_291 cfg91_292) /\ (z < 0 \/ g z (\x1_209.WALK x1_209 g cfg90_291 cfg91_292 k)))).
Forall p      =v ∀n. p n.
