/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/alt-inev.ml
*/

%HES
MAIN_30  =v LIFE arg1_598 0 0 (\r_292.\r1_293.\r2_294.r1_293 = 3 \/ r1_293 = 5).
APP h cfg50 cfg51 k =v
  k
   (\x1_587.
     \cfg60_588.
      \cfg61_589.
       \k_590.
        k_590
         (\x2_279.
           \cfg70_280.
            \cfg71_281.
             \k_282.
              h x1_587 cfg70_280 cfg71_281
               (\r_378.
                 \r1_379.
                  \r2_380.
                   r_378 (\j_489.\cfg40_490.\cfg41_491.\k_492.k_492 (j_489 - x2_279) cfg40_490 cfg41_491) r1_379 r2_380
                    k_282))
         cfg60_588 cfg61_589)
   cfg50 cfg51.
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 \/ evx != 1) /\ (cfg00 != 1 \/ evx != 1) \/ k 1 0)
  /\ ((cfg00 = 0 /\ evx = 1 \/ cfg00 = 1 /\ evx = 1)
      \/ ((cfg00 != 1 \/ evx != 2) /\ (cfg00 != 2 \/ evx != 2) \/ k 2 0)
         /\ ((cfg00 = 1 /\ evx = 2 \/ cfg00 = 2 /\ evx = 2)
             \/ ((cfg00 != 2 \/ evx != 3) \/ k 3 0)
                /\ (cfg00 = 2 /\ evx = 3
                    \/ ((cfg00 != 1 \/ evx != 4) /\ (cfg00 != 4 \/ evx != 4) \/ k 4 0)
                       /\ ((cfg00 = 1 /\ evx = 4 \/ cfg00 = 4 /\ evx = 4)
                           \/ ((cfg00 != 4 \/ evx != 5) \/ k 5 0) /\ (cfg00 = 4 /\ evx = 5 \/ k 6 0))))).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 >= 6 \/ k true) /\ cfg10 < 6.
LIFE x cfg290 cfg291 k =v
  Forall
   (\n_691.
     (n_691 != 0
      \/ EV_STEP0 1 cfg290 cfg291
          (\x0_595.
            \x1_596.
             EV_STEP_ASST0 x0_595 x1_596
              (\u_289.
                (x >= 0
                 \/ APP WALK x0_595 x1_596
                     (\x16_619.
                       \x161_620.
                        \x162_621.
                         x16_619 x x161_620 x162_621
                          (\x17_320.
                            \x171_321.
                             \x172_322.
                              x17_320 1 x171_321 x172_322
                               (\x18_427.
                                 \x181_428.
                                  \x182_429.
                                   EV_STEP0 3 x181_428 x182_429
                                    (\x01_507.\x11_508.EV_STEP_ASST0 x01_507 x11_508 (\u1_565.k true x01_507 x11_508))))))
                /\ (x < 0
                    \/ APP RUN x0_595 x1_596
                        (\x13_629.
                          \x131_630.
                           \x132_631.
                            x13_629 x x131_630 x132_631
                             (\x14_332.
                               \x141_333.
                                \x142_334.
                                 x14_332 1 x141_333 x142_334
                                  (\x15_441.
                                    \x151_442.
                                     \x152_443.
                                      EV_STEP0 5 x151_442 x152_443
                                       (\x01_523.
                                         \x11_524.EV_STEP_ASST0 x01_523 x11_524 (\u1_582.k true x01_523 x11_524)))))))))
     /\ (n_691 = 0 \/ LIFE x cfg290 cfg291 k)).
RUN y cfg210 cfg211 k =v
  k
   (\f_648.
     \cfg220_649.
      \cfg221_650.
       \k_651.
        EV_STEP0 4 cfg220_649 cfg221_650
         (\x0_358.
           \x1_359.
            EV_STEP_ASST0 x0_358 x1_359
             (\u_453.
               (y >= 0 \/ k_651 0 x0_358 x1_359)
               /\ (y < 0
                   \/ f_648 y x0_358 x1_359
                       (\x8_609.
                         \x81_610.
                          \x82_611.
                           f_648 x8_609 x81_610 x82_611
                            (\x9_308.
                              \x91_309.
                               \x92_310.
                                RUN x9_308 x91_309 x92_310
                                 (\x10_413.
                                   \x101_414.
                                    \x102_415.
                                     x10_413 f_648 x101_414 x102_415
                                      (\p0_534.\p10_535.\p11_536.k_651 0 p10_535 p11_536))))))))
   cfg210 cfg211.
WALK z cfg140 cfg141 k =v
  k
   (\g_655.
     \cfg150_656.
      \cfg151_657.
       \k_658.
        EV_STEP0 2 cfg150_656 cfg151_657
         (\x0_367.
           \x1_368.
            EV_STEP_ASST0 x0_367 x1_368
             (\u_463.
               (z >= 0 \/ k_658 0 x0_367 x1_368)
               /\ (z < 0
                   \/ g_655 z x0_367 x1_368
                       (\x4_642.
                         \x41_643.
                          \x42_644.
                           WALK x4_642 x41_643 x42_644
                            (\x5_348.
                              \x51_349.
                               \x52_350.
                                x5_348 g_655 x51_349 x52_350 (\p0_546.\p10_547.\p11_548.k_658 0 p10_547 p11_548)))))))
   cfg140 cfg141.
Forall p      =v ∀n. p n.
