/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/auction.ml
*/

%HES
MAIN_2  =v
  BID 1 1 (\x_149.\cfg150_150.\cfg1510_151.\cfg1511_152.\k_153.k_153 true cfg150_150 cfg1510_151 cfg1511_152) 0 0 0
   (\r_111.\r1_112.\r2_113.\r3_114.r1_112 = 0 \/ r1_112 = 1 /\ r3_114 = r2_113 - 1).
BID i amtW f cfg110 cfg1110 cfg1111 k =v
  Forall
   (\n_162.
     (n_162 != 0
      \/ EV_STEP0 1 cfg110 cfg1110 cfg1111
          (\cfg120_122.
            \cfg1210_123.
             \cfg1211_124.
              EV_STEP_ASST0 cfg120_122 cfg1210_123 cfg1211_124
               (\x_88.
                 BID (i + 1) (amtW + 1)
                  (\x_157.
                    \cfg30_158.
                     \cfg310_159.
                      \cfg311_160.
                       \k1_161.
                        (i > 1 \/ k1_161 true cfg30_158 cfg310_159 cfg311_160)
                        /\ (i <= 1
                            \/ EV_STEP0 3 cfg30_158 cfg310_159 cfg311_160
                                (\cfg40_142.
                                  \cfg410_143.
                                   \cfg411_144.
                                    EV_STEP_ASST0 cfg40_142 cfg410_143 cfg411_144
                                     (\x1_110.f true cfg40_142 cfg410_143 cfg411_144 k1_161))))
                  cfg120_122 cfg1210_123 cfg1211_124 k)))
     /\ (n_162 = 0
         \/ (i != 1 \/ k true cfg110 cfg1110 cfg1111)
            /\ (i = 1
                \/ EV_STEP0 2 cfg110 cfg1110 cfg1111
                    (\cfg80_131.
                      \cfg810_132.
                       \cfg811_133.
                        EV_STEP_ASST0 cfg80_131 cfg810_132 cfg811_133 (\x_98.f true cfg80_131 cfg810_132 cfg811_133 k))))).
EV_STEP0 evx cfg00 cfg010 cfg011 k =v
  ((cfg00 != 0 \/ evx != 1) \/ k cfg00 (cfg010 + 1) cfg011)
  /\ (cfg00 = 0 /\ evx = 1
      \/ ((cfg00 != 0 \/ evx != 2) \/ k 1 cfg010 cfg011)
         /\ (cfg00 = 0 /\ evx = 2
             \/ (((cfg00 != 1 \/ evx != 3) \/ cfg010 <= cfg011 + 1) \/ k 1 cfg010 (cfg011 + 1))
                /\ ((cfg00 = 1 /\ evx = 3) /\ cfg010 > cfg011 + 1 \/ k 2 cfg010 cfg011))).
EV_STEP_ASST0 cfg10 cfg110 cfg111 k =v (cfg10 >= 2 \/ k true) /\ cfg10 < 2.
Forall p      =v ∀n. p n.
