/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/auction.ml
*/

%HES
MAIN_20  =v
  BID 1 0 0 0
   (\x12_962.
     \x121_963.
      \x122_964.
       \x123_965.
        x12_962 1 x121_963 x122_964 x123_965
         (\x13_567.
           \x131_568.
            \x132_569.
             \x133_570.
              x13_567
               (\x_979.\cfg280_980.\cfg2810_981.\cfg2811_982.\k_983.k_983 true cfg280_980 cfg2810_981 cfg2811_982)
               x131_568 x132_569 x133_570
               (\p0_590.\p10_591.\p110_592.\p111_593.p10_591 = 0 \/ p10_591 = 1 /\ p111_593 = p110_592 - 1))).
BID i cfg150 cfg1510 cfg1511 k =v
  k
   (\amtW_970.
     \cfg160_971.
      \cfg1610_972.
       \cfg1611_973.
        \k_974.
         k_974
          (\f_579.
            \cfg170_580.
             \cfg1710_581.
              \cfg1711_582.
               \k_583.
                Forall
                 (\n_984.
                   (n_984 != 0
                    \/ EV_STEP0 1 cfg170_580 cfg1710_581 cfg1711_582
                        (\x0_680.
                          \x10_681.
                           \x11_682.
                            EV_STEP_ASST0 x0_680 x10_681 x11_682
                             (\u_726.
                               BID (i + 1) x0_680 x10_681 x11_682
                                (\x7_772.
                                  \x71_773.
                                   \x72_774.
                                    \x73_775.
                                     x7_772 (amtW_970 + 1) x71_773 x72_774 x73_775
                                      (\x8_827.
                                        \x81_828.
                                         \x82_829.
                                          \x83_830.
                                           x8_827
                                            (\x_355.
                                              \cfg60_356.
                                               \cfg610_357.
                                                \cfg611_358.
                                                 \k_359.
                                                  (i > 1 \/ k_359 true cfg60_356 cfg610_357 cfg611_358)
                                                  /\ (i <= 1
                                                      \/ EV_STEP0 3 cfg60_356 cfg610_357 cfg611_358
                                                          (\x01_474.
                                                            \x101_475.
                                                             \x111_476.
                                                              EV_STEP_ASST0 x01_474 x101_475 x111_476
                                                               (\u1_518.
                                                                 f_579 true x01_474 x101_475 x111_476
                                                                  (\r_560.
                                                                    \r1_561.
                                                                     \r2_562.\r3_563.k_359 true r1_561 r2_562 r3_563)))))
                                            x81_828 x82_829 x83_830
                                            (\p0_432.\p10_433.\p110_434.\p111_435.k_583 true p10_433 p110_434 p111_435))))))
                   /\ (n_984 = 0
                       \/ (i != 1 \/ k_583 true cfg170_580 cfg1710_581 cfg1711_582)
                          /\ (i = 1
                              \/ EV_STEP0 2 cfg170_580 cfg1710_581 cfg1711_582
                                  (\x0_703.
                                    \x10_704.
                                     \x11_705.
                                      EV_STEP_ASST0 x0_703 x10_704 x11_705
                                       (\u_750.
                                         f_579 true x0_703 x10_704 x11_705
                                          (\r_799.\r1_800.\r2_801.\r3_802.k_583 true r1_800 r2_801 r3_802)))))))
          cfg160_971 cfg1610_972 cfg1611_973)
   cfg150 cfg1510 cfg1511.
EV_STEP0 evx cfg00 cfg010 cfg011 k =v
  ((cfg00 != 0 \/ evx != 1) \/ k cfg00 (cfg010 + 1) cfg011)
  /\ (cfg00 = 0 /\ evx = 1
      \/ ((cfg00 != 0 \/ evx != 2) \/ k 1 cfg010 cfg011)
         /\ (cfg00 = 0 /\ evx = 2
             \/ (((cfg00 != 1 \/ evx != 3) \/ cfg010 <= cfg011 + 1) \/ k 1 cfg010 (cfg011 + 1))
                /\ ((cfg00 = 1 /\ evx = 3) /\ cfg010 > cfg011 + 1 \/ k 2 cfg010 cfg011))).
EV_STEP_ASST0 cfg10 cfg110 cfg111 k =v (cfg10 >= 2 \/ k true) /\ cfg10 < 2.
Forall p      =v ∀n. p n.
