/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 83930c1
  Z3 library: Z3 4.13.0.0
  Z3 binary: Z3 version 4.13.1 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.0
  Command: mochi.exe -trans HFLz ../tr_tuple_mochi/binomial_heap.ml
*/

%HES
MAIN_10  =v
  (arg1_370 < 0 \/ arg2_207 < 0)
  \/ EV_STEP0 arg1_370 arg2_207 arg1_370 0 0 0
      (\cfg160_366.
        \cfg1610_367.
         \cfg1611_368.
          EV_STEP_ASST0 arg1_370 arg2_207 cfg160_366 cfg1610_367 cfg1611_368
           (\x_204.
             INSTREE arg1_370 arg2_207 0 arg2_207 arg1_370 cfg160_366 cfg1610_367 cfg1611_368
              (\r_231.\r1_232.\r2_233.\r3_234.r3_234 = (arg1_370 - r2_233) + 1))).
EV_STEP0 prefh prefj evx cfg00 cfg010 cfg011 k =v
  (cfg00 != 0 \/ k 1 cfg010 evx)
  /\ (cfg00 = 0
      \/ ((cfg00 != 1 \/ evx != 1) \/ k cfg00 (cfg010 + 1) cfg011)
         /\ (cfg00 = 1 /\ evx = 1
             \/ ((cfg00 != 1 \/ evx != 2) \/ k cfg00 cfg010 (cfg011 - 1))
                /\ (cfg00 = 1 /\ evx = 2
                    \/ ((cfg00 != 1 \/ evx != 3) \/ k 2 cfg010 (cfg011 + 1))
                       /\ (cfg00 = 1 /\ evx = 3 \/ k 3 cfg010 cfg011)))).
EV_STEP_ASST0 prefh prefj cfg10 cfg110 cfg111 k =v (cfg10 >= 3 \/ k true) /\ cfg10 < 3.
INSTREE prefh prefj i k l cfg60 cfg610 cfg611 k1 =v
  (i < k
   \/ EV_STEP0 prefh prefj 3 cfg60 cfg610 cfg611
       (\cfg130_348.
         \cfg1310_349.
          \cfg1311_350.
           EV_STEP_ASST0 prefh prefj cfg130_348 cfg1310_349 cfg1311_350
            (\x_184.k1 (l + 1) cfg130_348 cfg1310_349 cfg1311_350)))
  /\ (i >= k
      \/ EV_STEP0 prefh prefj 2 cfg60 cfg610 cfg611
          (\cfg70_360.
            \cfg710_361.
             \cfg711_362.
              EV_STEP_ASST0 prefh prefj cfg70_360 cfg710_361 cfg711_362
               (\x_197.
                 EV_STEP0 prefh prefj 1 cfg70_360 cfg710_361 cfg711_362
                  (\cfg40_221.
                    \cfg410_222.
                     \cfg411_223.
                      EV_STEP_ASST0 prefh prefj cfg40_221 cfg410_222 cfg411_223
                       (\x1_251.INSTREE prefh prefj (i + 1) k (l - 1) cfg40_221 cfg410_222 cfg411_223 k1))))).
Forall p      =v ∀n. p n.
