/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/binomial_heap.ml
*/

%HES
MAIN_14  =v
  EV_STEP0 arg1_374 arg2_211 arg1_374 0 0 0
   (\cfg160_370.
     \cfg1610_371.
      \cfg1611_372.
       EV_STEP_ASST0 arg1_374 arg2_211 cfg160_370 cfg1610_371 cfg1611_372
        (\x_208.
          INSTREE arg1_374 arg2_211 0 arg2_211 arg1_374 cfg160_370 cfg1610_371 cfg1611_372
           (\p0_235.\p10_236.\p110_237.\p111_238.p111_238 = (arg1_374 - p110_237) + 1))).
EV_STEP0 prefh prefj evx cfg00 cfg010 cfg011 k =v
  (cfg00 != 0 \/ k 1 cfg010 evx)
  /\ (cfg00 = 0
      \/ ((cfg00 != 1 \/ evx != 1) \/ k cfg00 (cfg010 + 1) cfg011)
         /\ (cfg00 = 1 /\ evx = 1
             \/ ((cfg00 != 1 \/ evx != 2) \/ k cfg00 cfg010 (cfg011 - 1))
                /\ (cfg00 = 1 /\ evx = 2
                    \/ ((cfg00 != 1 \/ evx != 3) \/ k 2 cfg010 (cfg011 + 1))
                       /\ (cfg00 = 1 /\ evx = 3 \/ k 3 cfg010 cfg011)))).
EV_STEP_ASST0 prefh prefj cfg10 cfg110 cfg111 k =v (cfg10 >= 3 \/ k true) /\ cfg10 < 3.
INSTREE prefh prefj i k l cfg60 cfg610 cfg611 k1 =v
  (i < k
   \/ EV_STEP0 prefh prefj 3 cfg60 cfg610 cfg611
       (\cfg130_352.
         \cfg1310_353.
          \cfg1311_354.
           EV_STEP_ASST0 prefh prefj cfg130_352 cfg1310_353 cfg1311_354
            (\x_188.k1 (l + 1) cfg130_352 cfg1310_353 cfg1311_354)))
  /\ (i >= k
      \/ EV_STEP0 prefh prefj 2 cfg60 cfg610 cfg611
          (\cfg70_364.
            \cfg710_365.
             \cfg711_366.
              EV_STEP_ASST0 prefh prefj cfg70_364 cfg710_365 cfg711_366
               (\x_201.
                 EV_STEP0 prefh prefj 1 cfg70_364 cfg710_365 cfg711_366
                  (\cfg40_225.
                    \cfg410_226.
                     \cfg411_227.
                      EV_STEP_ASST0 prefh prefj cfg40_225 cfg410_226 cfg411_227
                       (\x1_255.INSTREE prefh prefj (i + 1) k (l - 1) cfg40_225 cfg410_226 cfg411_227 k1))))).
Forall p      =v ∀n. p n.
