/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/concurrent_sum.ml
*/

%HES
MAIN_10  =v SUM arg1_91 arg1_91 0 0 (\r_87.\r1_88.\r2_89.r1_88 = 0 /\ r2_89 <= 3 * arg1_91).
BR_CHOOSE_38 prefn x cfg20 cfg21 k =v
  ((((cfg20 != 0 \/ 1 > 3) \/ k 0 0 (1 + cfg21)) /\ (cfg20 = 0 /\ 1 <= 3 \/ k 0 1 cfg21))
   /\ (((cfg20 != 0 \/ 2 > 3) \/ k 0 0 (2 + cfg21)) /\ (cfg20 = 0 /\ 2 <= 3 \/ k 0 1 cfg21)))
  /\ (((cfg20 != 0 \/ 3 > 3) \/ k 0 0 (3 + cfg21)) /\ (cfg20 = 0 /\ 3 <= 3 \/ k 0 1 cfg21)).
SUM prefn n cfg30 cfg31 k =v
  (n != 0 \/ k 0 cfg30 cfg31)
  /\ (n = 0 \/ BR_CHOOSE_38 prefn true cfg30 cfg31 (\r_97.\r1_98.\r2_99.SUM prefn (n - 1) r1_98 r2_99 k)).
Forall p      =v ∀n. p n.
