/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/depend.ml
*/

%HES
MAIN_5  =v arg1_37 != 0 \/ (1 <= arg1_37 \/ 0 + 1 >= 0) /\ (1 > arg1_37 \/ 0 >= 0).
Forall p      =v ∀n. p n.
