/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/disj.ml
*/

%HES
MAIN_10  =v
  (arg2_93 <= 0 \/ arg3_115 >= 0) \/ F arg1_120 arg2_93 arg3_115 0 0 (\main0_116.\main10_117.\main11_118.true).
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 /\ cfg00 != 1 \/ evx <= 0) \/ k 1 0)
  /\ ((cfg00 = 0 \/ cfg00 = 1) /\ evx > 0
      \/ ((cfg00 != 1 \/ evx >= 0) \/ k 3 0)
         /\ (cfg00 = 1 /\ evx < 0
             \/ ((cfg00 != 0 /\ cfg00 != 2 \/ evx >= 0) \/ k 2 0) /\ ((cfg00 = 0 \/ cfg00 = 2) /\ evx < 0 \/ k 3 0))).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 >= 3 \/ k true) /\ cfg10 < 3.
F x pos neg cfg20 cfg21 k =v
  Forall
   (\n_150.
     (n_150 != 0
      \/ EV_STEP0 pos cfg20 cfg21
          (\cfg40_127.
            \cfg41_128.
             EV_STEP_ASST0 cfg40_127 cfg41_128
              (\x1_102.(x > 0 \/ k 0 cfg40_127 cfg41_128) /\ (x <= 0 \/ F (x - 2) pos neg cfg40_127 cfg41_128 k))))
     /\ (n_150 = 0
         \/ EV_STEP0 neg cfg20 cfg21
             (\cfg30_135.
               \cfg31_136.
                EV_STEP_ASST0 cfg30_135 cfg31_136
                 (\x1_111.(x > 0 \/ k 0 cfg30_135 cfg31_136) /\ (x <= 0 \/ F (x - 2) pos neg cfg30_135 cfg31_136 k))))).
Forall p      =v ∀n. p n.
