/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/disj-nondet.ml
*/

%HES
MAIN_11  =v
  (arg2_110 <= 0 \/ arg3_134 >= 0)
  \/ Forall
      (\n_177.
        (n_177 != 0 \/ F arg1_144 1 arg2_110 arg3_134 0 0 (\main0_135.\main10_136.\main11_137.true))
        /\ (n_177 = 0 \/ F arg1_144 0 arg2_110 arg3_134 0 0 (\main0_135.\main10_136.\main11_137.true))).
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 /\ cfg00 != 1 \/ evx <= 0) \/ k 1 0)
  /\ ((cfg00 = 0 \/ cfg00 = 1) /\ evx > 0
      \/ ((cfg00 != 1 \/ evx >= 0) \/ k 3 0)
         /\ (cfg00 = 1 /\ evx < 0
             \/ ((cfg00 != 0 /\ cfg00 != 2 \/ evx >= 0) \/ k 2 0) /\ ((cfg00 = 0 \/ cfg00 = 2) /\ evx < 0 \/ k 3 0))).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 >= 3 \/ k true) /\ cfg10 < 3.
F x b pos neg cfg20 cfg21 k =v
  (b != 0
   \/ EV_STEP0 pos cfg20 cfg21
       (\cfg40_152.
         \cfg41_153.
          EV_STEP_ASST0 cfg40_152 cfg41_153
           (\x1_120.(x > 0 \/ k 0 cfg40_152 cfg41_153) /\ (x <= 0 \/ F (x - 1) b pos neg cfg40_152 cfg41_153 k))))
  /\ (b = 0
      \/ EV_STEP0 neg cfg20 cfg21
          (\cfg30_161.
            \cfg31_162.
             EV_STEP_ASST0 cfg30_161 cfg31_162
              (\x1_130.(x > 0 \/ k 0 cfg30_161 cfg31_162) /\ (x <= 0 \/ F (x - 1) b pos neg cfg30_161 cfg31_162 k)))).
Forall p      =v ∀n. p n.
