/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/disj-gte.ml
*/

%HES
MAIN_10  =v
  (arg2_107 <= 0 \/ arg3_129 >= 0) \/ F arg1_134 arg2_107 arg3_129 0 0 (\main0_130.\main10_131.\main11_132.true).
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 /\ cfg00 != 1 \/ evx <= 0) \/ k 1 0)
  /\ ((cfg00 = 0 \/ cfg00 = 1) /\ evx > 0
      \/ ((cfg00 != 1 \/ evx >= 0) \/ k 3 0)
         /\ (cfg00 = 1 /\ evx < 0
             \/ ((cfg00 != 0 /\ cfg00 != 2 \/ evx >= 0) \/ k 2 0) /\ ((cfg00 = 0 \/ cfg00 = 2) /\ evx < 0 \/ k 3 0))).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 >= 3 \/ k true) /\ cfg10 < 3.
F x pos neg cfg20 cfg21 k =v
  (x <= 0
   \/ EV_STEP0 pos cfg20 cfg21
       (\cfg40_141.
         \cfg41_142.
          EV_STEP_ASST0 cfg40_141 cfg41_142
           (\x1_116.
             (x <= 0 \/ F (x - 1) pos neg cfg40_141 cfg41_142 k)
             /\ (x > 0 \/ (x >= 0 \/ F (x + 1) pos neg cfg40_141 cfg41_142 k) /\ (x < 0 \/ k 0 cfg40_141 cfg41_142)))))
  /\ (x > 0
      \/ (x >= 0
          \/ EV_STEP0 neg cfg20 cfg21
              (\cfg30_149.
                \cfg31_150.
                 EV_STEP_ASST0 cfg30_149 cfg31_150
                  (\x1_125.
                    (x <= 0 \/ F (x - 1) pos neg cfg30_149 cfg31_150 k)
                    /\ (x > 0
                        \/ (x >= 0 \/ F (x + 1) pos neg cfg30_149 cfg31_150 k) /\ (x < 0 \/ k 0 cfg30_149 cfg31_150)))))
         /\ (x < 0
             \/ (x <= 0 \/ F (x - 1) pos neg cfg20 cfg21 k)
                /\ (x > 0 \/ (x >= 0 \/ F (x + 1) pos neg cfg20 cfg21 k) /\ (x < 0 \/ k 0 cfg20 cfg21)))).
Forall p      =v ∀n. p n.
