/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/disj-nondet.ml
*/

%HES
MAIN_22  =v
  (arg2_242 <= 0 \/ arg3_321 >= 0)
  \/ Forall
      (\n_504.
        (n_504 != 0
         \/ F arg1_418 0 0
             (\x5_237.
               \x51_238.
                \x52_239.
                 x5_237 1 x51_238 x52_239
                  (\x6_315.
                    \x61_316.
                     \x62_317.
                      x6_315 arg2_242 x61_316 x62_317
                       (\p0_369.
                         \p10_370.\p11_371.p0_369 arg3_321 p10_370 p11_371 (\main0_407.\main10_408.\main11_409.true)))))
        /\ (n_504 = 0
            \/ F arg1_418 0 0
                (\x5_237.
                  \x51_238.
                   \x52_239.
                    x5_237 0 x51_238 x52_239
                     (\x6_315.
                       \x61_316.
                        \x62_317.
                         x6_315 arg2_242 x61_316 x62_317
                          (\p0_369.
                            \p10_370.\p11_371.p0_369 arg3_321 p10_370 p11_371 (\main0_407.\main10_408.\main11_409.true)))))).
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 /\ cfg00 != 1 \/ evx <= 0) \/ k 1 0)
  /\ ((cfg00 = 0 \/ cfg00 = 1) /\ evx > 0
      \/ ((cfg00 != 1 \/ evx >= 0) \/ k 3 0)
         /\ (cfg00 = 1 /\ evx < 0
             \/ ((cfg00 != 0 /\ cfg00 != 2 \/ evx >= 0) \/ k 2 0) /\ ((cfg00 = 0 \/ cfg00 = 2) /\ evx < 0 \/ k 3 0))).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 >= 3 \/ k true) /\ cfg10 < 3.
F x cfg20 cfg21 k =v
  k
   (\b_226.
     \cfg30_227.
      \cfg31_228.
       \k_229.
        k_229
         (\pos_302.
           \cfg40_303.
            \cfg41_304.
             \k_305.
              k_305
               (\neg_354.
                 \cfg50_355.
                  \cfg51_356.
                   \k_357.
                    (b_226 != 0
                     \/ EV_STEP0 pos_302 cfg50_355 cfg51_356
                         (\x0_451.
                           \x1_452.
                            EV_STEP_ASST0 x0_451 x1_452
                             (\u_279.
                               (x > 0 \/ k_357 0 x0_451 x1_452)
                               /\ (x <= 0
                                   \/ F (x - 1) x0_451 x1_452
                                       (\x2_435.
                                         \x21_436.
                                          \x22_437.
                                           x2_435 b_226 x21_436 x22_437
                                            (\x3_261.
                                              \x31_262.
                                               \x32_263.
                                                x3_261 pos_302 x31_262 x32_263
                                                 (\x4_342.
                                                   \x41_343.
                                                    \x42_344.
                                                     x4_342 neg_354 x41_343 x42_344
                                                      (\p01_404.\p101_405.\p111_406.k_357 0 p101_405 p111_406))))))))
                    /\ (b_226 = 0
                        \/ EV_STEP0 neg_354 cfg50_355 cfg51_356
                            (\x0_466.
                              \x1_467.
                               EV_STEP_ASST0 x0_466 x1_467
                                (\u_295.
                                  (x > 0 \/ k_357 0 x0_466 x1_467)
                                  /\ (x <= 0
                                      \/ F (x - 1) x0_466 x1_467
                                          (\x2_435.
                                            \x21_436.
                                             \x22_437.
                                              x2_435 b_226 x21_436 x22_437
                                               (\x3_261.
                                                 \x31_262.
                                                  \x32_263.
                                                   x3_261 pos_302 x31_262 x32_263
                                                    (\x4_342.
                                                      \x41_343.
                                                       \x42_344.
                                                        x4_342 neg_354 x41_343 x42_344
                                                         (\p01_404.\p101_405.\p111_406.k_357 0 p101_405 p111_406)))))))))
               cfg40_303 cfg41_304)
         cfg30_227 cfg31_228)
   cfg20 cfg21.
Forall p      =v ∀n. p n.
