/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/higher-order.ml
*/

%HES
MAIN_13  =v
  APPLY (\x_175.\cfg70_176.\cfg71_177.\k_178.k_178 (x_175 - 1) cfg70_176 cfg71_177) 0 0
   (\x3_83.
     \x31_84.
      \x32_85.
       x3_83 arg1_147 x31_84 x32_85 (\u_102.\u1_103.\u2_104.EV_STEP0 2 u1_103 u2_104 (\x0_126.\x1_127.x0_126 = 2))).
APPLY f cfg20 cfg21 k =v
  k
   (\x_142.
     \cfg30_143.
      \cfg31_144.
       \k_145.
        (x_142 > 0 \/ EV_STEP0 1 cfg30_143 cfg31_144 (\x0_154.\x1_155.k_145 0 x0_154 x1_155))
        /\ (x_142 <= 0
            \/ EV_STEP0 1 cfg30_143 cfg31_144
                (\x0_163.
                  \x1_164.
                   APPLY f x0_163 x1_164
                    (\x01_95.
                      \x02_96.
                       \x03_97.
                        f x_142 x02_96 x03_97
                         (\x11_116.
                           \x12_117.
                            \x13_118.x01_95 x11_116 x12_117 x13_118 (\p0_78.\p10_79.\p11_80.k_145 0 p10_79 p11_80))))))
   cfg20 cfg21.
EV_STEP0 evx cfg00 cfg01 k =v
  ((evx != 1 \/ cfg00 != 0 /\ cfg00 != 1) \/ k 1 0)
  /\ (evx = 1 /\ (cfg00 = 0 \/ cfg00 = 1) \/ ((evx != 2 \/ cfg00 != 1) \/ k 2 0) /\ (evx = 2 /\ cfg00 = 1 \/ k 3 0)).
Forall p      =v ∀n. p n.
