/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/higher-order.ml
*/

%HES
MAIN_10  =v
  APPLY (\x_93.\k_94.k_94 (x_93 - 1)) arg1_89 0 0
   (\x1_56.\x11_57.\x12_58.EV_STEP0 2 x11_57 x12_58 (\x0_64.\x13_65.x0_64 = 2)).
APPLY f x cfg20 cfg21 k =v
  (x > 0 \/ EV_STEP0 1 cfg20 cfg21 (\x0_79.\x1_80.k 0 x0_79 x1_80))
  /\ (x <= 0 \/ EV_STEP0 1 cfg20 cfg21 (\x0_86.\x1_87.f x (\x2_53.APPLY f x2_53 x0_86 x1_87 k))).
EV_STEP0 evx cfg00 cfg01 k =v
  ((evx != 1 \/ cfg00 != 0 /\ cfg00 != 1) \/ k 1 0)
  /\ (evx = 1 /\ (cfg00 = 0 \/ cfg00 = 1) \/ ((evx != 2 \/ cfg00 != 1) \/ k 2 0) /\ (evx = 2 /\ cfg00 = 1 \/ k 3 0)).
Forall p      =v ∀n. p n.
