/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/intro-ord3.ml
*/

%HES
MAIN_7  =v
  EV_STEP0 arg1_81 0 0
   (\cfg70_78.
     \cfg71_79.
      EV_STEP_ASST0 cfg70_78 cfg71_79
       (\x_62.
         APP3 0
          (\cx_46.
            \cfg50_47.
             \cfg51_48.
              \k_49.
               EV_STEP0 cx_46 cfg50_47 cfg51_48
                (\cfg60_73.\cfg61_74.EV_STEP_ASST0 cfg60_73 cfg61_74 (\x_56.k_49 x_56 cfg60_73 cfg61_74)))
          0 (\ab_33.\af_34.\cfg40_35.\cfg41_36.\k_37.af_34 arg1_81 cfg40_35 cfg41_36 k_37) arg2_65 cfg70_78 cfg71_79
          (\main0_66.\main10_67.\main11_68.true))).
APP3 b f a g k cfg30 cfg31 k1 =v
  (k <= 0 \/ APP3 0 (\sx_90.\cfg20_91.\cfg21_92.\k_93.f (sx_90 + 1) cfg20_91 cfg21_92 k_93) 0 g (k - 1) cfg30 cfg31 k1)
  /\ (k > 0 \/ g 0 f cfg30 cfg31 k1).
EV_STEP0 evx cfg00 cfg01 k =v
  (cfg00 != 0 \/ k 1 evx)
  /\ (cfg00 = 0 \/ ((cfg00 != 1 \/ evx < cfg01) \/ k 1 cfg01) /\ (cfg00 = 1 /\ evx >= cfg01 \/ k 2 cfg01)).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 >= 2 \/ k true) /\ cfg10 < 2.
Forall p      =v ∀n. p n.
