/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/last-ev-even.ml
*/

%HES
MAIN_6  =v FOO arg1_61 0 0 0 (\p0_36.\p10_37.\p11_38.Forall (\n_63.n_63 = 0)).
FOO vv f cfg20 cfg21 k =v (vv != 0 \/ k 0 0 0) /\ (vv = 0 \/ FOO (vv - 1) 0 0 0 k).
Forall p      =v ∀n. p n.
