/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/last-ev-even.ml
*/

%HES
MAIN_12  =v
  (n_158 != 0
   \/ FOO arg1_138 0 0
       (\x4_142.\x41_143.\x42_144.x4_142 0 x41_143 x42_144 (\p0_134.\p10_135.\p11_136.Forall (\n_159.n_159 = 0))))
  /\ (n_158 = 0
      \/ FOO arg1_138 0 0
          (\x2_148.\x21_149.\x22_150.x2_148 0 x21_149 x22_150 (\p0_134.\p10_135.\p11_136.Forall (\n_160.n_160 = 0)))).
FOO vv cfg20 cfg21 k =v
  k
   (\f_127.
     \cfg30_128.
      \cfg31_129.
       \k_130.
        (vv != 0 \/ k_130 0 0 0)
        /\ (vv = 0
            \/ FOO (vv - 1) 0 0
                (\x01_106.
                  \x02_107.\x03_108.x01_106 0 x02_107 x03_108 (\p0_120.\p10_121.\p11_122.k_130 0 p10_121 p11_122))))
   cfg20 cfg21.
Forall p      =v ∀n. p n.
