/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/lics18-web.ml
*/

%HES
MAIN_8  =v LISTENER 0 arg1_212 0 0 0 0 (\main_177.true).
EV_STEP0 evx cfg00 cfg010 cfg011 k =v
  (((cfg00 != 0 \/ cfg011 >= 42) \/ evx != 1) \/ k 0 (cfg010 + 1) (cfg011 + 1))
  /\ ((cfg00 = 0 /\ cfg011 < 42) /\ evx = 1
      \/ (((cfg00 != 0 \/ cfg011 >= 42) \/ evx != 2) \/ k 0 (cfg010 - 1) (cfg011 + 1))
         /\ ((cfg00 = 0 /\ cfg011 < 42) /\ evx = 2
             \/ (((cfg00 != 0 \/ cfg011 >= 42) \/ evx != 3) \/ k 0 cfg010 (cfg011 + 1))
                /\ ((cfg00 = 0 /\ cfg011 < 42) /\ evx = 3
                    \/ (((cfg00 != 0 \/ cfg011 != 42) \/ evx != 1) \/ k 42 (cfg010 + 1) 43)
                       /\ ((cfg00 = 0 /\ cfg011 = 42) /\ evx = 1
                           \/ (((cfg00 != 0 \/ cfg011 != 42) \/ evx != 2) \/ k 42 (cfg010 - 1) 43)
                              /\ ((cfg00 = 0 /\ cfg011 = 42) /\ evx = 2
                                  \/ (((cfg00 != 0 \/ cfg011 != 42) \/ evx != 3) \/ k 42 cfg010 43)
                                     /\ ((cfg00 = 0 /\ cfg011 = 42) /\ evx = 3
                                         \/ (((cfg00 != 42 \/ evx != 2) \/ cfg010 != 1) \/ k 0 0 0)
                                            /\ ((cfg00 = 42 /\ evx = 2) /\ cfg010 = 1
                                                \/ ((cfg00 != 42 \/ evx != 2) \/ k 42 (cfg010 - 1) (cfg011 - 1))
                                                   /\ (cfg00 = 42 /\ evx = 2
                                                       \/ (cfg00 != 42 /\ cfg00 != 666 \/ k 666 0 0)
                                                          /\ ((cfg00 = 42 \/ cfg00 = 666) \/ k cfg00 cfg010 cfg011))))))))).
EV_STEP_ASST0 cfg10 cfg110 cfg111 k =v
  (cfg10 != 666 /\ cfg110 > cfg111 \/ k true) /\ (cfg10 = 666 \/ cfg110 <= cfg111).
K_LISTENER cfg20 cfg210 cfg211 i npool pend k x =v
  (x = 0
   \/ EV_STEP0 1 cfg20 cfg210 cfg211
       (\cfg90_186.
         \cfg910_187.
          \cfg911_188.
           EV_STEP_ASST0 cfg90_186 cfg910_187 cfg911_188
            (\x1_152.LISTENER 0 npool (pend + 1) cfg90_186 cfg910_187 cfg911_188 k)))
  /\ (x != 0
      \/ (pend <= 0
          \/ EV_STEP0 2 cfg20 cfg210 cfg211
              (\cfg60_197.
                \cfg610_198.
                 \cfg611_199.
                  EV_STEP_ASST0 cfg60_197 cfg610_198 cfg611_199
                   (\x1_164.LISTENER 0 npool (pend - 1) cfg60_197 cfg610_198 cfg611_199 k)))
         /\ (pend > 0
             \/ EV_STEP0 3 cfg20 cfg210 cfg211
                 (\cfg30_208.
                   \cfg310_209.
                    \cfg311_210.
                     EV_STEP_ASST0 cfg30_208 cfg310_209 cfg311_210
                      (\x1_176.LISTENER 0 npool pend cfg30_208 cfg310_209 cfg311_210 k)))).
LISTENER i npool pend cfg20 cfg210 cfg211 k =v
  Forall
   (\n_216.
     (\f_218.(pend >= npool \/ f_218 1) /\ (pend < npool \/ f_218 0))
      (\x_217.
        (n_216 != 0 \/ K_LISTENER cfg20 cfg210 cfg211 i npool pend k x_217)
        /\ (n_216 = 0 \/ K_LISTENER cfg20 cfg210 cfg211 i npool pend k 0))).
Forall p      =v ∀n. p n.
