/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/lics18-hoshrink.ml
*/

%HES
MAIN_18  =v
  (arg2_132 = 0
   \/ SHRINK arg2_132 arg1_204 0 (\x_153.\k_154.k_154 arg1_204) arg2_132 0 (0 + arg1_204 / arg2_132)
       (\r_200.
         \r1_201.
          \r2_202.
           (\f_242.(r2_202 != arg1_204 / arg2_132 \/ f_242 true) /\ (r2_202 = arg1_204 / arg2_132 \/ f_242 false))
            (\x_241.(arg2_132 = 0 \/ r2_202 = arg1_204 / arg2_132) /\ arg2_132 != 0)))
  /\ arg2_132 != 0.
SHRINK prefgl prefgl1 t f d cfg20 cfg21 k =v
  f true
   (\x_217.
     (x_217 > 0 \/ k 0 cfg20 cfg21)
     /\ (x_217 <= 0 \/ f true (\x1_147.SHRINK prefgl prefgl1 0 (\x3_188.\k_189.k_189 (x1_147 - d)) d 0 (cfg21 + 1) k))).
Forall p      =v ∀n. p n.
