/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/lics18-amortized.ml
*/

%HES
MAIN_16  =v
  ENQUEUE arg2_163 arg3_183 arg1_259 arg1_259 arg2_163 arg3_183 0 0 0 0
   (\x9_252.
     \x91_253.
      \x92_254.
       \x93_255.
        \x94_256.
         \x95_257.
          DEQUEUE arg2_163 arg3_183 arg1_259 x9_252 x91_253 x92_254 x93_255 x94_256 x95_257
           (\p0_156.
             \p10_157.
              \p110_158.
               \p111_159.\p112_160.(p10_157 = 0 /\ p112_160 = p110_158 + arg3_183) /\ p112_160 = p111_159 - arg2_163)).
AUX cfg20 cfg210 cfg211 cfg212 l prefl1 prefl2 prefn l1 l2 cfg30 cfg310 cfg311 cfg312 k =v
  (l1 != 0 \/ k l2 cfg30 cfg310 cfg311 cfg312)
  /\ (l1 = 0
      \/ EV_STEP0 prefl1 prefl2 prefn 2 cfg30 cfg310 cfg311 cfg312
          (\x0_200.
            \x10_201.
             \x11_202.
              \x12_203.
               AUX cfg20 cfg210 cfg211 cfg212 l prefl1 prefl2 prefn (l1 - 1) (l2 + 1) x0_200 x10_201 x11_202 x12_203 k)).
DEQUEUE prefl1 prefl2 prefn x30 x31 cfg50 cfg510 cfg511 cfg512 k =v
  (x30 <= 0
   \/ EV_STEP0 prefl1 prefl2 prefn 1 cfg50 cfg510 cfg511 cfg512
       (\x0_214.\x10_215.\x11_216.\x12_217.DEQUEUE prefl1 prefl2 prefn (x30 - 1) x31 x0_214 x10_215 x11_216 x12_217 k))
  /\ (x30 > 0
      \/ ((x30 != 0 \/ x31 <= 0)
          \/ AUX cfg50 cfg510 cfg511 cfg512 x31 prefl1 prefl2 prefn x31 0 cfg50 cfg510 cfg511 cfg512
              (\x5_228.
                \x51_229.
                 \x52_230.\x53_231.\x54_232.DEQUEUE prefl1 prefl2 prefn x5_228 0 x51_229 x52_230 x53_231 x54_232 k))
         /\ (x30 = 0 /\ x31 > 0 \/ k 0 cfg50 cfg510 cfg511 cfg512)).
ENQUEUE prefl1 prefl2 prefn n x20 x21 cfg90 cfg910 cfg911 cfg912 k =v
  (n != 0 \/ k x20 x21 cfg90 cfg910 cfg911 cfg912)
  /\ (n = 0
      \/ EV_STEP0 prefl1 prefl2 prefn 0 cfg90 cfg910 cfg911 cfg912
          (\x0_244.
            \x10_245.
             \x11_246.\x12_247.ENQUEUE prefl1 prefl2 prefn (n - 1) x20 (x21 + 1) x0_244 x10_245 x11_246 x12_247 k)).
EV_STEP0 prefl1 prefl2 prefn evx cfg00 cfg010 cfg011 cfg012 k =v
  ((cfg00 != 0 \/ evx != 0) \/ k cfg00 (cfg010 + 1) cfg011 cfg012)
  /\ (cfg00 = 0 /\ evx = 0
      \/ ((cfg00 != 0 \/ evx != 1) \/ k cfg00 cfg010 (cfg011 + 1) cfg012)
         /\ (cfg00 = 0 /\ evx = 1
             \/ ((cfg00 != 0 \/ evx != 2) \/ k cfg00 cfg010 cfg011 (cfg012 + 1))
                /\ (cfg00 = 0 /\ evx = 2 \/ k 1 cfg010 cfg011 cfg012))).
Forall p      =v ∀n. p n.
