/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 83930c1
  Z3 library: Z3 4.13.0.0
  Z3 binary: Z3 version 4.13.1 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.0
  Command: mochi.exe -trans HFLz ../tr_tuple_mochi/lics18-amortized.ml
*/

%HES
MAIN_16  =v
  (arg2_163 < 0 \/ arg3_183 < 0)
  \/ ENQUEUE arg2_163 arg3_183 arg1_259 arg1_259 arg2_163 arg3_183 0 0 0 0
      (\r_252.
        \r1_253.
         \r2_254.
          \r3_255.
           \r4_256.
            \r5_257.
             DEQUEUE arg2_163 arg3_183 arg1_259 r_252 r1_253 r2_254 r3_255 r4_256 r5_257
              (\r6_156.
                \r7_157.
                 \r8_158.\r9_159.\r10_160.(r7_157 = 0 /\ r10_160 = r8_158 + arg3_183) /\ r10_160 = r9_159 - arg2_163)).
AUX cfg20 cfg210 cfg211 cfg212 l prefl1 prefl2 prefn l1 l2 cfg30 cfg310 cfg311 cfg312 k =v
  (l1 != 0 \/ k l2 cfg30 cfg310 cfg311 cfg312)
  /\ (l1 = 0
      \/ EV_STEP0 prefl1 prefl2 prefn 2 cfg30 cfg310 cfg311 cfg312
          (\x0_200.
            \x10_201.
             \x11_202.
              \x12_203.
               AUX cfg20 cfg210 cfg211 cfg212 l prefl1 prefl2 prefn (l1 - 1) (l2 + 1) x0_200 x10_201 x11_202 x12_203 k)).
DEQUEUE prefl1 prefl2 prefn x30 x31 cfg50 cfg510 cfg511 cfg512 k =v
  (x30 <= 0
   \/ EV_STEP0 prefl1 prefl2 prefn 1 cfg50 cfg510 cfg511 cfg512
       (\x0_214.\x10_215.\x11_216.\x12_217.DEQUEUE prefl1 prefl2 prefn (x30 - 1) x31 x0_214 x10_215 x11_216 x12_217 k))
  /\ (x30 > 0
      \/ ((x30 != 0 \/ x31 <= 0)
          \/ AUX cfg50 cfg510 cfg511 cfg512 x31 prefl1 prefl2 prefn x31 0 cfg50 cfg510 cfg511 cfg512
              (\r_228.\r1_229.\r2_230.\r3_231.\r4_232.DEQUEUE prefl1 prefl2 prefn r_228 0 r1_229 r2_230 r3_231 r4_232 k))
         /\ (x30 = 0 /\ x31 > 0 \/ k 0 cfg50 cfg510 cfg511 cfg512)).
ENQUEUE prefl1 prefl2 prefn n x20 x21 cfg90 cfg910 cfg911 cfg912 k =v
  (n != 0 \/ k x20 x21 cfg90 cfg910 cfg911 cfg912)
  /\ (n = 0
      \/ EV_STEP0 prefl1 prefl2 prefn 0 cfg90 cfg910 cfg911 cfg912
          (\x0_244.
            \x10_245.
             \x11_246.\x12_247.ENQUEUE prefl1 prefl2 prefn (n - 1) x20 (x21 + 1) x0_244 x10_245 x11_246 x12_247 k)).
EV_STEP0 prefl1 prefl2 prefn evx cfg00 cfg010 cfg011 cfg012 k =v
  ((cfg00 != 0 \/ evx != 0) \/ k cfg00 (cfg010 + 1) cfg011 cfg012)
  /\ (cfg00 = 0 /\ evx = 0
      \/ ((cfg00 != 0 \/ evx != 1) \/ k cfg00 cfg010 (cfg011 + 1) cfg012)
         /\ (cfg00 = 0 /\ evx = 1
             \/ ((cfg00 != 0 \/ evx != 2) \/ k cfg00 cfg010 cfg011 (cfg012 + 1))
                /\ (cfg00 = 0 /\ evx = 2 \/ k 1 cfg010 cfg011 cfg012))).
Forall p      =v ∀n. p n.
