/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/lics18-hoshrink.ml
*/

%HES
MAIN_23  =v
  (arg2_272 = 0
   \/ SHRINK arg2_272 arg1_501 0 0 (0 + arg1_501 / arg2_272)
       (\x8_530.
         \x81_531.
          \x82_532.
           x8_530 (\x_295.\cfg160_296.\cfg161_297.\k_298.k_298 arg1_501 cfg160_296 cfg161_297) x81_531 x82_532
            (\x9_520.
              \x91_521.
               \x92_522.
                x9_520 arg2_272 x91_521 x92_522
                 (\x10_505.
                   \x101_506.
                    \x102_507.
                     (\f_566.
                       (x102_507 != arg1_501 / arg2_272 \/ f_566 true)
                       /\ (x102_507 = arg1_501 / arg2_272 \/ f_566 false))
                      (\x_565.(arg2_272 = 0 \/ x102_507 = arg1_501 / arg2_272) /\ arg2_272 != 0)))))
  /\ arg2_272 != 0.
SHRINK prefgl prefgl1 t cfg20 cfg21 k =v
  k
   (\f_513.
     \cfg30_514.
      \cfg31_515.
       \k_516.
        k_516
         (\d_281.
           \cfg40_282.
            \cfg41_283.
             \k_284.
              f_513 true cfg40_282 cfg41_283
               (\x0_311.
                 \x01_312.
                  \x02_313.
                   (x0_311 > 0 \/ k_284 0 x01_312 x02_313)
                   /\ (x0_311 <= 0
                       \/ f_513 true 0 (x02_313 + 1)
                           (\x5_371.
                             \x51_372.
                              \x52_373.
                               SHRINK prefgl prefgl1 0 x51_372 x52_373
                                (\x3_424.
                                  \x31_425.
                                   \x32_426.
                                    x3_424
                                     (\x_453.
                                       \cfg100_454.\cfg101_455.\k_456.k_456 (x5_371 - d_281) cfg100_454 cfg101_455)
                                     x31_425 x32_426
                                     (\x4_484.
                                       \x41_485.
                                        \x42_486.
                                         x4_484 d_281 x41_485 x42_486
                                          (\p01_260.\p101_261.\p111_262.k_284 0 p101_261 p111_262)))))))
         cfg30_514 cfg31_515)
   cfg20 cfg21.
Forall p      =v ∀n. p n.
