/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/market.ml
*/

%HES
MAIN_28  =v
  (1 < 0 \/ (1 < 0 \/ (1 <= 0 \/ (1 < 1 \/ 1 < 1))))
  \/ ACTIVITY SELL 0 0 0
      (\x19_465.
        \x191_466.
         \x192_467.
          \x193_468.
           x19_465 (0 - 1) x191_466 x192_467 x193_468
            (\p0_208.
              \p10_209.
               \p110_210.
                \p111_211.
                 ACTIVITY BUY p10_209 p110_210 p111_211
                  (\x22_271.
                    \x221_272.
                     \x222_273.
                      \x223_274.
                       x22_271 (0 - 1) x221_272 x222_273 x223_274
                        (\x23_346.
                          \x231_347.
                           \x232_348.
                            \x233_349.REPEAT 1 x231_347 x232_348 x233_349 (\x24_400.\x241_401.\x242_402.\x243_403.true))))).
ACTIVITY f cfg160 cfg1610 cfg1611 k =v
  k
   (\n3_435.
     \cfg170_436.
      \cfg1710_437.
       \cfg1711_438.
        \k_439.
         f n3_435 cfg170_436 cfg1710_437 cfg1711_438
          (\r_188.
            \r1_189.
             \r2_190.
              \r3_191.
               EV_STEP0 0 r1_189 r2_190 r3_191
                (\x0_245.
                  \x10_246.\x11_247.EV_STEP_ASST0 x0_245 x10_246 x11_247 (\u_318.k_439 true x0_245 x10_246 x11_247))))
   cfg160 cfg1610 cfg1611.
BUY n2 cfg90 cfg910 cfg911 k =v
  EV_STEP0 1 cfg90 cfg910 cfg911
   (\x0_445.
     \x10_446.
      \x11_447.
       EV_STEP_ASST0 x0_445 x10_446 x11_447
        (\u_200.
          EV_STEP0 n2 x0_445 x10_446 x11_447
           (\x01_257.
             \x101_258.\x111_259.EV_STEP_ASST0 x01_257 x101_258 x111_259 (\u1_331.k true x01_257 x101_258 x111_259)))).
EV_STEP0 evx cfg00 cfg010 cfg011 k =v
  (((cfg00 != 0 \/ evx <= 0) \/ evx >= 3) \/ k evx cfg010 cfg011)
  /\ ((cfg00 = 0 /\ evx > 0) /\ evx < 3
      \/ (cfg00 != 1
          \/ Forall
              (\x_453.
                (\f_493.(x_453 != 0 \/ f_493 1) /\ (x_453 = 0 \/ f_493 0))
                 (\x_492.K_EV_STEP0_25 cfg00 cfg010 cfg011 evx k x_492)))
         /\ (cfg00 = 1 \/ K_EV_STEP0_25 cfg00 cfg010 cfg011 evx k 0)).
EV_STEP_ASST0 cfg10 cfg110 cfg111 k =v
  ((((cfg10 >= 3 \/ cfg110 < 0) \/ cfg111 < 0) \/ cfg111 < cfg110) \/ k true)
  /\ (((cfg10 < 3 /\ cfg110 >= 0) /\ cfg111 >= 0) /\ cfg111 >= cfg110).
K_EV_STEP0 cfg00 cfg010 cfg011 evx x k x1 =v
  (x1 = 0 \/ k cfg00 cfg010 (cfg011 - evx))
  /\ (x1 != 0
      \/ ((cfg00 != 1 /\ cfg00 != 2 \/ evx != 0) \/ k 0 cfg010 cfg011)
         /\ ((cfg00 = 1 \/ cfg00 = 2) /\ evx = 0 \/ k 3 cfg010 cfg011)).
K_EV_STEP0_25 cfg00 cfg010 cfg011 evx k x =v
  (x = 0 \/ k cfg00 (cfg010 - evx) cfg011)
  /\ (x != 0
      \/ (cfg00 != 2
          \/ Forall
              (\x1_460.
                (\f_495.(x1_460 != 0 \/ f_495 1) /\ (x1_460 = 0 \/ f_495 0))
                 (\x_494.K_EV_STEP0 cfg00 cfg010 cfg011 evx x k x_494)))
         /\ (cfg00 = 2 \/ K_EV_STEP0 cfg00 cfg010 cfg011 evx x k 0)).
REPEAT n4 cfg230 cfg2310 cfg2311 k =v
  (n4 > 0 \/ k 0 cfg230 cfg2310 cfg2311)
  /\ (n4 <= 0
      \/ ACTIVITY BUY cfg230 cfg2310 cfg2311
          (\x12_474.
            \x121_475.
             \x122_476.
              \x123_477.
               x12_474 1 x121_475 x122_476 x123_477
                (\p0_220.
                  \p10_221.
                   \p110_222.
                    \p111_223.
                     ACTIVITY SELL p10_221 p110_222 p111_223
                      (\x15_287.
                        \x151_288.
                         \x152_289.
                          \x153_290.
                           x15_287 1 x151_288 x152_289 x153_290
                            (\x16_365.
                              \x161_366.
                               \x162_367.
                                \x163_368.
                                 REPEAT (n4 - 1) x161_366 x162_367 x163_368
                                  (\x18_423.\x181_424.\x182_425.\x183_426.k 0 x181_424 x182_425 x183_426)))))).
SELL n1 cfg20 cfg210 cfg211 k =v
  EV_STEP0 2 cfg20 cfg210 cfg211
   (\x0_483.
     \x10_484.
      \x11_485.
       EV_STEP_ASST0 x0_483 x10_484 x11_485
        (\u_232.
          EV_STEP0 n1 x0_483 x10_484 x11_485
           (\x01_300.
             \x101_301.\x111_302.EV_STEP_ASST0 x01_300 x101_301 x111_302 (\u1_381.k true x01_300 x101_301 x111_302)))).
Forall p      =v ∀n. p n.
