/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 83930c1
  Z3 library: Z3 4.13.0.0
  Z3 binary: Z3 version 4.13.1 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.0
  Command: mochi.exe -trans HFLz ../tr_tuple_mochi/market.ml
*/

%HES
MAIN_24  =v
  ((arg1_309 < 0 \/ (arg2_172 < 0 \/ arg3_223 <= 0)) \/ (arg2_172 < arg1_309 \/ arg1_309 < arg3_223))
  \/ ACTIVITY SELL (0 - arg2_172) 0 0 0
      (\r_304.
        \r1_305.
         \r2_306.
          \r3_307.
           ACTIVITY BUY (0 - arg1_309) r1_305 r2_306 r3_307
            (\r4_166.
              \r5_167.
               \r6_168.
                \r7_169.REPEAT arg3_223 r5_167 r6_168 r7_169 (\main0_279.\main10_280.\main110_281.\main111_282.true))).
ACTIVITY f n3 cfg140 cfg1410 cfg1411 k =v
  f n3 cfg140 cfg1410 cfg1411
   (\r_288.
     \r1_289.
      \r2_290.
       \r3_291.
        EV_STEP0 0 r1_289 r2_290 r3_291
         (\cfg160_146.
           \cfg1610_147.
            \cfg1611_148.
             EV_STEP_ASST0 cfg160_146 cfg1610_147 cfg1611_148 (\x_207.k true cfg160_146 cfg1610_147 cfg1611_148))).
BUY n2 cfg80 cfg810 cfg811 k =v
  EV_STEP0 1 cfg80 cfg810 cfg811
   (\cfg90_297.
     \cfg910_298.
      \cfg911_299.
       EV_STEP_ASST0 cfg90_297 cfg910_298 cfg911_299
        (\x_157.
          EV_STEP0 n2 cfg90_297 cfg910_298 cfg911_299
           (\cfg110_217.
             \cfg1110_218.
              \cfg1111_219.
               EV_STEP_ASST0 cfg110_217 cfg1110_218 cfg1111_219 (\x1_265.k true cfg110_217 cfg1110_218 cfg1111_219)))).
EV_STEP0 evx cfg00 cfg010 cfg011 k =v
  (((cfg00 != 0 \/ evx <= 0) \/ evx >= 3) \/ k evx cfg010 cfg011)
  /\ ((cfg00 = 0 /\ evx > 0) /\ evx < 3
      \/ ((cfg00 != 1 \/ evx = 0) \/ k cfg00 (cfg010 - evx) cfg011)
         /\ (cfg00 = 1 /\ evx != 0
             \/ ((cfg00 != 2 \/ evx = 0) \/ k cfg00 cfg010 (cfg011 - evx))
                /\ (cfg00 = 2 /\ evx != 0
                    \/ ((cfg00 != 1 /\ cfg00 != 2 \/ evx != 0) \/ k 0 cfg010 cfg011)
                       /\ ((cfg00 = 1 \/ cfg00 = 2) /\ evx = 0 \/ k 3 cfg010 cfg011)))).
EV_STEP_ASST0 cfg10 cfg110 cfg111 k =v
  ((((cfg10 >= 3 \/ cfg110 < 0) \/ cfg111 < 0) \/ cfg111 < cfg110) \/ k true)
  /\ (((cfg10 < 3 /\ cfg110 >= 0) /\ cfg111 >= 0) /\ cfg111 >= cfg110).
REPEAT n4 cfg190 cfg1910 cfg1911 k =v
  (n4 > 0 \/ k 0 cfg190 cfg1910 cfg1911)
  /\ (n4 <= 0
      \/ ACTIVITY BUY 1 cfg190 cfg1910 cfg1911
          (\r_315.
            \r1_316.
             \r2_317.
              \r3_318.
               ACTIVITY SELL 1 r1_316 r2_317 r3_318
                (\r4_182.
                  \r5_183.
                   \r6_184.
                    \r7_185.
                     REPEAT (n4 - 1) r5_183 r6_184 r7_185
                      (\r8_237.\r9_238.\r10_239.\r11_240.k 0 r9_238 r10_239 r11_240)))).
SELL n1 cfg20 cfg210 cfg211 k =v
  EV_STEP0 2 cfg20 cfg210 cfg211
   (\cfg30_324.
     \cfg310_325.
      \cfg311_326.
       EV_STEP_ASST0 cfg30_324 cfg310_325 cfg311_326
        (\x_194.
          EV_STEP0 n1 cfg30_324 cfg310_325 cfg311_326
           (\cfg50_250.
             \cfg510_251.
              \cfg511_252.
               EV_STEP_ASST0 cfg50_250 cfg510_251 cfg511_252 (\x1_278.k true cfg50_250 cfg510_251 cfg511_252)))).
Forall p      =v ∀n. p n.
