/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/max-min.ml
*/

%HES
MAIN_9  =v
  ((arg1_118 < 0 \/ arg1_118 > 100000) /\ (arg1_118 >= 0 \/ arg1_118 < (-100000))
   \/ COMPUTE arg1_118 (0 - arg1_118)
       (\t_67.\k_68.(arg1_118 < 0 \/ k_68 (t_67 - 1)) /\ (arg1_118 >= 0 \/ k_68 (t_67 + 1))) 0 (-100000) 100000
       (\p0_113.\p10_114.\p110_115.\p111_116.p110_115 + p111_116 = 0))
  /\ ((arg1_118 >= 0 /\ arg1_118 <= 100000 \/ arg1_118 < 0 /\ arg1_118 >= (-100000)) \/ (-100000) + 100000 = 0).
COMPUTE vv bound1 inc cfg20 cfg210 cfg211 k =v
  (vv != bound1 \/ EV_STEP0 vv cfg20 cfg210 cfg211 (\x0_96.\x10_97.\x11_98.k 0 x0_96 x10_97 x11_98))
  /\ (vv = bound1
      \/ EV_STEP0 vv cfg20 cfg210 cfg211
          (\x0_106.\x10_107.\x11_108.inc vv (\x_79.COMPUTE x_79 bound1 inc x0_106 x10_107 x11_108 k))).
EV_STEP0 evx cfg00 cfg010 cfg011 k =v
  ((evx >= cfg011 \/ evx <= cfg010) \/ k 0 evx evx)
  /\ (evx < cfg011 /\ evx > cfg010
      \/ (evx >= cfg011 \/ k 0 cfg010 evx)
         /\ (evx < cfg011 \/ (evx <= cfg010 \/ k 0 evx cfg011) /\ (evx > cfg010 \/ k 0 cfg010 cfg011))).
Forall p      =v ∀n. p n.
