/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/monotonic.ml
*/

%HES
MAIN_9  =v arg1_50 <= 0 \/ MONO 1 arg1_50 0 0 (\p0_46.\p10_47.\p11_48.p10_47 = 0).
MONO t x cfg20 cfg21 k =v
  (x > 0 \/ ((cfg20 != 0 \/ t < cfg21) \/ k 0 0 t) /\ (cfg20 = 0 /\ t >= cfg21 \/ k 0 1 0))
  /\ (x <= 0
      \/ ((cfg20 != 0 \/ t < cfg21) \/ MONO (t + x) (x - 1) 0 t k)
         /\ (cfg20 = 0 /\ t >= cfg21 \/ MONO (t + x) (x - 1) 1 0 k)).
Forall p      =v ∀n. p n.
