/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/monotonic.ml
*/

%HES
MAIN_14  =v
  arg1_99 <= 0
  \/ MONO 1 0 0 (\x2_127.\x21_128.\x22_129.x2_127 arg1_99 x21_128 x22_129 (\p0_95.\p10_96.\p11_97.p10_96 = 0)).
MONO t cfg20 cfg21 k =v
  k
   (\x_103.
     \cfg30_104.
      \cfg31_105.
       \k_106.
        (x_103 > 0
         \/ ((cfg30_104 != 0 \/ t < cfg31_105) \/ k_106 0 0 t) /\ (cfg30_104 = 0 /\ t >= cfg31_105 \/ k_106 0 1 0))
        /\ (x_103 <= 0
            \/ ((cfg30_104 != 0 \/ t < cfg31_105)
                \/ MONO (t + x_103) 0 t
                    (\x01_89.
                      \x02_90.\x03_91.x01_89 (x_103 - 1) x02_90 x03_91 (\p0_77.\p10_78.\p11_79.k_106 0 p10_78 p11_79)))
               /\ (cfg30_104 = 0 /\ t >= cfg31_105
                   \/ MONO (t + x_103) 1 0
                       (\x01_89.
                         \x02_90.
                          \x03_91.x01_89 (x_103 - 1) x02_90 x03_91 (\p0_77.\p10_78.\p11_79.k_106 0 p10_78 p11_79)))))
   cfg20 cfg21.
Forall p      =v ∀n. p n.
