/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/nondet_max.ml
*/

%HES
MAIN_6  =v MAKE_LIST arg1_76 arg1_76 (GET_RANDOM_INT arg1_76) 0 0 (\main0_72.\main10_73.\main11_74.true).
GET_RANDOM_INT prefn n1 k =v
  (n1 != 0 \/ k 0) /\ (n1 = 0 \/ Forall (\n_89.(n_89 != 0 \/ GET_RANDOM_INT prefn (n1 - 1) k) /\ (n_89 = 0 \/ k n1))).
MAKE_LIST prefn n f cfg20 cfg21 k =v
  (n != 0 \/ k 0 cfg20 cfg21)
  /\ (n = 0
      \/ f n
          (\x_83.
            ((cfg20 != 0 \/ x_83 < cfg21) \/ (x_83 > prefn \/ MAKE_LIST prefn (n - 1) f 0 x_83 k) /\ x_83 <= prefn)
            /\ (cfg20 = 0 /\ x_83 >= cfg21
                \/ (cfg20 != 0 \/ (cfg21 > prefn \/ MAKE_LIST prefn (n - 1) f 0 cfg21 k) /\ cfg21 <= prefn)
                   /\ (cfg20 = 0
                       \/ ((cfg20 != 0 \/ cfg21 > prefn) \/ MAKE_LIST prefn (n - 1) f cfg20 cfg21 k)
                          /\ (cfg20 = 0 /\ cfg21 <= prefn))))).
Forall p      =v ∀n. p n.
