/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 83930c1
  Z3 library: Z3 4.13.3.0
  Z3 binary: Z3 version 4.11.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz num_evens.ml
*/

%HES
MAIN_7  =v F arg1_85 arg1_85 0 0 0 (\main0_81.\main10_82.\main11_83.true).
F m m1 flag cfg20 cfg21 k =v
  (m1 != 0 \/ k true cfg20 cfg21)
  /\ (m1 = 0
      \/ (\f_111.(flag != 1 \/ f_111 (F m (m1 - 1) 0 1 cfg21 k)) /\ (flag = 1 \/ f_111 (F m (m1 - 1) 1 1 cfg21 k)))
          (\x_108.
            (\f_110.
              (flag != 1 \/ f_110 (F m (m1 - 1) 0 0 (cfg21 + 1) k))
              /\ (flag = 1 \/ f_110 (F m (m1 - 1) 1 0 (cfg21 + 1) k)))
             (\x_109.
               (flag != 1
                \/ (cfg20 != 0
                    \/ (2 * (cfg21 + 1) > m
                        \/ (flag != 1 \/ F m (m1 - 1) 0 0 (cfg21 + 1) k)
                           /\ (flag = 1 \/ F m (m1 - 1) 1 0 (cfg21 + 1) k))
                       /\ 2 * (cfg21 + 1) <= m)
                   /\ cfg20 = 0)
               /\ (flag = 1
                   \/ (flag != 1 \/ F m (m1 - 1) 0 cfg20 cfg21 k) /\ (flag = 1 \/ F m (m1 - 1) 1 cfg20 cfg21 k))))).
Forall p      =v ∀n. p n.
