/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 83930c1
  Z3 library: Z3 4.13.0.0
  Z3 binary: Z3 version 4.13.1 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.0
  Command: mochi.exe -trans HFLz ../tr_tuple_mochi/order-irrel.ml
*/

%HES
MAIN_8  =v arg2_71 <= 0 \/ ORDER arg1_88 arg2_71 0 0 (\r_84.\r1_85.\r2_86.r1_85 = 0).
K_ORDER c cfg20 cfg21 d k x =v
  (cfg20 != 1 \/ ORDER (d - 2) c 1 cfg21 k)
  /\ (cfg20 = 1
      \/ (cfg21 != 0 \/ ORDER (d - 2) c cfg20 x k)
         /\ (cfg21 = 0 \/ (cfg21 != x \/ ORDER (d - 2) c cfg20 cfg21 k) /\ (cfg21 = x \/ ORDER (d - 2) c 1 cfg21 k))).
ORDER d c cfg20 cfg21 k =v
  (d <= 0
   \/ Forall (\n_95.(n_95 != 0 \/ K_ORDER c cfg20 cfg21 d k c) /\ (n_95 = 0 \/ K_ORDER c cfg20 cfg21 d k (0 - c))))
  /\ (d > 0 \/ k 0 cfg20 cfg21).
Forall p      =v ∀n. p n.
