/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/order-irrel-nondet.ml
*/

%HES
MAIN_9  =v
  (n_123 != 0 \/ ORDER arg1_109 arg2_91 1 0 0 (\r_105.\r1_106.\r2_107.r1_106 = 0))
  /\ (n_123 = 0 \/ ORDER arg1_109 arg2_91 0 0 0 (\r_105.\r1_106.\r2_107.r1_106 = 0)).
K_ORDER b c cfg20 cfg21 d k x =v
  (cfg20 != 1 \/ ORDER (d - 2) c b 1 cfg21 k)
  /\ (cfg20 = 1
      \/ (cfg21 != 0 \/ ORDER (d - 2) c b cfg20 x k)
         /\ (cfg21 = 0 \/ (cfg21 != x \/ ORDER (d - 2) c b cfg20 cfg21 k) /\ (cfg21 = x \/ ORDER (d - 2) c b 1 cfg21 k))).
ORDER d c b cfg20 cfg21 k =v
  (d <= 0 \/ (b != 1 \/ K_ORDER b c cfg20 cfg21 d k c) /\ (b = 1 \/ K_ORDER b c cfg20 cfg21 d k (0 - c)))
  /\ (d > 0 \/ k 0 cfg20 cfg21).
Forall p      =v ∀n. p n.
