/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/order-irrel.ml
*/

%HES
MAIN_6  =v ORDER arg1_86 arg2_62 0 0 (\r_66.\r1_67.\r2_68.r1_67 = 0).
K_ORDER c cfg20 cfg21 d k x =v
  (cfg20 != 1 \/ ORDER (d - 2) c 1 cfg21 k)
  /\ (cfg20 = 1
      \/ (cfg21 != 0 \/ ORDER (d - 2) c cfg20 x k)
         /\ (cfg21 = 0 \/ (cfg21 != x \/ ORDER (d - 2) c cfg20 cfg21 k) /\ (cfg21 = x \/ ORDER (d - 2) c 1 cfg21 k))).
ORDER d c cfg20 cfg21 k =v
  (d <= 0
   \/ Forall (\n_90.(n_90 != 0 \/ K_ORDER c cfg20 cfg21 d k c) /\ (n_90 = 0 \/ K_ORDER c cfg20 cfg21 d k (0 - c))))
  /\ (d > 0 \/ k 0 cfg20 cfg21).
Forall p      =v ∀n. p n.
