/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/overview1.ml
*/

%HES
MAIN_10  =v EV_STEP0 arg1_82 0 0 (\x0_79.\x1_80.BUSY arg2_58 arg1_82 x0_79 x1_80 (\r_53.\r1_54.\r2_55.r1_54 = 2)).
BUSY n t cfg20 cfg21 k =v
  (n > 0 \/ EV_STEP0 (0 - t) cfg20 cfg21 (\x0_74.\x1_75.k 0 x0_74 x1_75)) /\ (n <= 0 \/ BUSY (n - 1) t cfg20 cfg21 k).
EV_STEP0 evx cfg00 cfg01 k =v
  (cfg00 != 0 \/ k 1 evx)
  /\ (cfg00 = 0
      \/ ((cfg00 != 1 \/ cfg01 + evx != 0) /\ cfg00 != 2 \/ k 2 cfg01)
         /\ ((cfg00 = 1 /\ cfg01 + evx = 0 \/ cfg00 = 2) \/ k cfg00 cfg01)).
Forall p      =v ∀n. p n.
