/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/overview1.ml
*/

%HES
MAIN_11  =v
  EV_STEP0 arg1_129 0 0
   (\x0_126.
     \x1_127.
      BUSY arg2_93 x0_126 x1_127
       (\x11_88.\x12_89.\x13_90.x11_88 arg1_129 x12_89 x13_90 (\x2_101.\x21_102.\x22_103.x21_102 = 2))).
BUSY n cfg20 cfg21 k =v
  k
   (\t_119.
     \cfg30_120.
      \cfg31_121.
       \k_122.
        (n > 0 \/ EV_STEP0 (0 - t_119) cfg30_120 cfg31_121 (\x0_71.\x1_72.k_122 0 x0_71 x1_72))
        /\ (n <= 0 \/ BUSY (n - 1) cfg30_120 cfg31_121 (\r_80.\r1_81.\r2_82.r_80 t_119 r1_81 r2_82 k_122)))
   cfg20 cfg21.
EV_STEP0 evx cfg00 cfg01 k =v
  (cfg00 != 0 \/ k 1 evx)
  /\ (cfg00 = 0
      \/ ((cfg00 != 1 \/ cfg01 + evx != 0) /\ cfg00 != 2 \/ k 2 cfg01)
         /\ ((cfg00 = 1 /\ cfg01 + evx = 0 \/ cfg00 = 2) \/ k cfg00 cfg01)).
Forall p      =v ∀n. p n.
