/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/reentr.ml
*/

%HES
MAIN_11  =v
  REENT arg1_148 0 0
   (\r_86.
     \r1_87.
      \r2_88.EV_STEP0 (-1) r1_87 r2_88 (\cfg100_115.\cfg101_116.EV_STEP_ASST0 cfg100_115 cfg101_116 (\x_132.true))).
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 \/ cfg01 + evx < 0) \/ k cfg00 (cfg01 + evx))
  /\ (cfg00 = 0 /\ cfg01 + evx >= 0
      \/ ((cfg00 != 0 \/ cfg01 + evx >= 0) \/ k 1 (cfg01 + evx)) /\ (cfg00 = 0 /\ cfg01 + evx < 0 \/ k cfg00 cfg01)).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 != 0 \/ k true) /\ cfg10 = 0.
K_REENT cfg20 cfg21 cfg30 cfg31 d x k x1 =v
  (x1 = 0
   \/ REENT (d - 1) cfg30 cfg31
       (\r_144.
         \r1_145.
          \r2_146.
           EV_STEP0 (-1) r1_145 r2_146
            (\cfg60_82.\cfg61_83.EV_STEP_ASST0 cfg60_82 cfg61_83 (\x2_109.k x2_109 cfg60_82 cfg61_83))))
  /\ (x1 != 0 \/ k true cfg30 cfg31).
REENT d cfg20 cfg21 k =v
  EV_STEP0 1 cfg20 cfg21
   (\cfg30_153.
     \cfg31_154.
      EV_STEP_ASST0 cfg30_153 cfg31_154
       (\x_95.
         (d <= 0
          \/ Forall
              (\x1_124.
                (\f_159.(x1_124 != 0 \/ f_159 1) /\ (x1_124 = 0 \/ f_159 0))
                 (\x_158.K_REENT cfg20 cfg21 cfg30_153 cfg31_154 d x_95 k x_158)))
         /\ (d > 0 \/ K_REENT cfg20 cfg21 cfg30_153 cfg31_154 d x_95 k 0))).
Forall p      =v ∀n. p n.
