/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/reentr.ml
*/

%HES
MAIN_13  =v
  arg1_161 <= 0
  \/ REENT arg1_161 0 0
      (\r_157.\r1_158.\r2_159.EV_STEP0 (-1) r1_158 r2_159 (\x0_100.\x1_101.EV_STEP_ASST0 x0_100 x1_101 (\u_130.true))).
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 \/ cfg01 + evx < 0) \/ k cfg00 (cfg01 + evx))
  /\ (cfg00 = 0 /\ cfg01 + evx >= 0
      \/ ((cfg00 != 0 \/ cfg01 + evx >= 0) \/ k 1 (cfg01 + evx)) /\ (cfg00 = 0 /\ cfg01 + evx < 0 \/ k cfg00 cfg01)).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 != 0 \/ k true) /\ cfg10 = 0.
K_REENT_P cfg20 cfg21 d u x0 x1 k x =v
  (x = 0
   \/ REENT (d - 1) x0 x1
       (\x2_152.
         \x21_153.
          \x22_154.
           EV_STEP0 (-1) x21_153 x22_154 (\x01_93.\x11_94.EV_STEP_ASST0 x01_93 x11_94 (\u1_122.k true x01_93 x11_94))))
  /\ (x != 0 \/ k true x0 x1).
REENT d cfg20 cfg21 k =v
  EV_STEP0 1 cfg20 cfg21
   (\x0_174.
     \x1_175.
      EV_STEP_ASST0 x0_174 x1_175
       (\u_108.
         (d <= 0
          \/ Forall
              (\x_169.
                (\f_189.(x_169 != 0 \/ f_189 1) /\ (x_169 = 0 \/ f_189 0))
                 (\x_188.
                   K_REENT_P cfg20 cfg21 d u_108 x0_174 x1_175 (\p0_138.\p10_139.\p11_140.k true p10_139 p11_140) x_188)))
         /\ (d > 0 \/ K_REENT_P cfg20 cfg21 d u_108 x0_174 x1_175 (\p0_138.\p10_139.\p11_140.k true p10_139 p11_140) 0))).
Forall p      =v ∀n. p n.
