/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 83930c1
  Z3 library: Z3 4.13.0.0
  Z3 binary: Z3 version 4.13.1 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.0
  Command: mochi.exe -trans HFLz ../tr_tuple_mochi/reentr.ml
*/

%HES
MAIN_13  =v
  arg1_150 <= 0
  \/ REENT arg1_150 0 0
      (\r_146.
        \r1_147.
         \r2_148.EV_STEP0 (-1) r1_147 r2_148 (\cfg100_91.\cfg101_92.EV_STEP_ASST0 cfg100_91 cfg101_92 (\x_121.true))).
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 \/ cfg01 + evx < 0) \/ k cfg00 (cfg01 + evx))
  /\ (cfg00 = 0 /\ cfg01 + evx >= 0
      \/ ((cfg00 != 0 \/ cfg01 + evx >= 0) \/ k 1 (cfg01 + evx)) /\ (cfg00 = 0 /\ cfg01 + evx < 0 \/ k cfg00 cfg01)).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 != 0 \/ k true) /\ cfg10 = 0.
K_REENT cfg20 cfg21 cfg30 cfg31 d x k x1 =v
  (x1 = 0
   \/ REENT (d - 1) cfg30 cfg31
       (\r_141.
         \r1_142.
          \r2_143.
           EV_STEP0 (-1) r1_142 r2_143
            (\cfg60_84.\cfg61_85.EV_STEP_ASST0 cfg60_84 cfg61_85 (\x2_113.k x2_113 cfg60_84 cfg61_85))))
  /\ (x1 != 0 \/ k true cfg30 cfg31).
REENT d cfg20 cfg21 k =v
  EV_STEP0 1 cfg20 cfg21
   (\cfg30_155.
     \cfg31_156.
      EV_STEP_ASST0 cfg30_155 cfg31_156
       (\x_99.
         (d <= 0
          \/ Forall
              (\x1_129.
                (\f_163.(x1_129 != 0 \/ f_163 1) /\ (x1_129 = 0 \/ f_163 0))
                 (\x_162.K_REENT cfg20 cfg21 cfg30_155 cfg31_156 d x_99 k x_162)))
         /\ (d > 0 \/ K_REENT cfg20 cfg21 cfg30_155 cfg31_156 d x_99 k 0))).
Forall p      =v ∀n. p n.
