/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/resource-analysis.ml
*/

%HES
MAIN_8  =v
  (arg1_63 <= arg2_46 \/ arg2_46 < 0)
  \/ EV_STEP_ASST0 0 (0 + arg1_63) (\x_43.SPEND arg2_46 0 (0 + arg1_63) (\main0_54.\main10_55.\main11_56.true)).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg11 < 0 \/ k true) /\ cfg11 >= 0.
SPEND n cfg20 cfg21 k =v
  EV_STEP_ASST0 0 (cfg21 + (-1))
   (\x_53.(n > 0 \/ k 0 0 (cfg21 + (-1))) /\ (n <= 0 \/ SPEND (n - 1) 0 (cfg21 + (-1)) k)).
Forall p      =v ∀n. p n.
