/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/resource-analysis.ml
*/

%HES
MAIN_10  =v
  (arg1_98 <= arg2_62 \/ arg2_62 < 0)
  \/ EV_STEP_ASST0 0 (0 + arg1_98) (\u_59.SPEND arg2_62 0 (0 + arg1_98) (\r_76.\r1_77.\r2_78.true)).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg11 < 0 \/ k true) /\ cfg11 >= 0.
SPEND n cfg20 cfg21 k =v
  EV_STEP_ASST0 0 (cfg21 + (-1))
   (\u_69.
     (n > 0 \/ k 0 0 (cfg21 + (-1)))
     /\ (n <= 0 \/ SPEND (n - 1) 0 (cfg21 + (-1)) (\p0_86.\p10_87.\p11_88.k 0 p10_87 p11_88))).
Forall p      =v ∀n. p n.
