/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/sum-of-ev-even.ml
*/

%HES
MAIN_6  =v
  (n_45 != 0 \/ SUM arg1_34 0 0 (\p0_37.\p10_38.\p11_39.Forall (\n_46.n_46 = 0)))
  /\ (n_45 = 0 \/ SUM (arg1_34 + 1) 0 0 (\p0_37.\p10_38.\p11_39.Forall (\n_47.n_47 = 0))).
SUM x cfg30 cfg31 k =v (x > 0 \/ k 0 0 0) /\ (x <= 0 \/ SUM (x - 2) 0 0 k).
Forall p      =v ∀n. p n.
