/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/sum-appendix.ml
*/

%HES
MAIN_3  =v
  EV_STEP_ASST0 0 (2 + 0)
   (\x_180.
     EV_STEP_ASST0 0 (3 + (2 + 0))
      (\x1_191.
        EV_STEP_ASST0 0 (1 + (3 + (2 + 0)))
         (\x2_208.
           EV_STEP_ASST0 0 (4 + (1 + (3 + (2 + 0))))
            (\x3_260.
              EV_STEP_ASST0 0 ((10 + 20) + (4 + (1 + (3 + (2 + 0)))))
               (\x6_158.(10 + 20) + (4 + (1 + (3 + (2 + 0)))) = 40))))).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg11 < 0 \/ k true) /\ cfg11 >= 0.
Forall p      =v ∀n. p n.
