/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/sum-of-ev-even.ml
*/

%HES
MAIN_10  =v
  (n_65 != 0 \/ SUM arg1_48 0 0 (\p0_44.\p10_45.\p11_46.Forall (\n_66.n_66 = 0)))
  /\ (n_65 = 0 \/ SUM (arg1_48 + 1) 0 0 (\p0_44.\p10_45.\p11_46.Forall (\n_67.n_67 = 0))).
SUM x cfg30 cfg31 k =v (x > 0 \/ k 0 0 0) /\ (x <= 0 \/ SUM (x - 2) 0 0 (\p0_53.\p10_54.\p11_55.k 0 p10_54 p11_55)).
Forall p      =v ∀n. p n.
