/*
Generated by
MoCHi: Model Checker for Higher-Order Programs
  Build: 10b9033
  Z3 library: Z3 4.15.2.0
  Z3 binary: Z3 version 4.15.2 - 64 bit
  HorSat2 version: 0.95
  HoIce version: 1.10.0
  OCaml version: 4.14.1
  Command: mochi.exe -trans HFLz ../../tests/effects/tr_tuple_mochi/temperature.ml
*/

%HES
MAIN_10  =v
  (arg2_100 <= 0 \/ arg3_122 >= 0) \/ F arg1_127 arg2_100 arg3_122 0 0 (\main0_123.\main10_124.\main11_125.true).
EV_STEP0 evx cfg00 cfg01 k =v
  ((cfg00 != 0 \/ evx <= 0) \/ k 1 evx)
  /\ (cfg00 = 0 /\ evx > 0
      \/ ((cfg00 != 0 \/ evx >= 0) \/ k 2 evx)
         /\ (cfg00 = 0 /\ evx < 0
             \/ ((cfg00 != 1 \/ evx <= cfg01) \/ k 1 evx)
                /\ (cfg00 = 1 /\ evx > cfg01
                    \/ ((cfg00 != 2 \/ evx >= cfg01) \/ k 2 evx) /\ (cfg00 = 2 /\ evx < cfg01 \/ k 3 evx)))).
EV_STEP_ASST0 cfg10 cfg11 k =v (cfg10 >= 3 \/ k true) /\ cfg10 < 3.
F x pos neg cfg20 cfg21 k =v
  Forall
   (\n_157.
     (n_157 != 0
      \/ EV_STEP0 pos cfg20 cfg21
          (\cfg40_134.
            \cfg41_135.
             EV_STEP_ASST0 cfg40_134 cfg41_135
              (\x1_109.
                (x > 0 \/ k 0 cfg40_134 cfg41_135) /\ (x <= 0 \/ F (x - 2) (pos + 1) (neg - 1) cfg40_134 cfg41_135 k))))
     /\ (n_157 = 0
         \/ EV_STEP0 neg cfg20 cfg21
             (\cfg30_142.
               \cfg31_143.
                EV_STEP_ASST0 cfg30_142 cfg31_143
                 (\x1_118.
                   (x > 0 \/ k 0 cfg30_142 cfg31_143)
                   /\ (x <= 0 \/ F (x - 2) (pos + 1) (neg - 1) cfg30_142 cfg31_143 k))))).
Forall p      =v ∀n. p n.
